In [47]:
import pandas as pd
from sklearn import metrics
from sklearn.model_selection import train_test_split
from sklearn.metrics import recall_score
from sklearn.metrics import classification_report 
from sklearn.metrics import confusion_matrix
from sklearn.tree import DecisionTreeClassifier

sklearn (scikit-learn): A popular library for machine learning.

metrics: Tools to measure how good your model is.

train_test_split: Splits your data into two parts:

Training data (to teach the computer).

Testing data (to check if it learned correctly).

recall_score, classification_report, confusion_matrix: Different ways to measure performance (like giving your model a report card).

DecisionTreeClassifier: A type of machine learning model that makes decisions by asking yes/no questions (like a flowchart).

In [48]:
df = pd.read_csv('tel_churn_cleaned.csv')
df.head()

,Unnamed: 0,SeniorCitizen,MonthlyCharges,TotalCharges,Churn,gender_Female,gender_Male,Partner_No,Partner_Yes,Dependents_No,...,PaymentMethod_Bank transfer (automatic),PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check,tenure_group_1 - 12,tenure_group_13 - 24,tenure_group_25 - 36,tenure_group_37 - 48,tenure_group_49 - 60,tenure_group_61 - 72
0,0,0,29.85,29.85,0,True,False,False,True,True,...,False,False,True,False,True,False,False,False,False,False
1,1,0,56.95,1889.50,0,False,True,True,False,True,...,False,False,False,True,False,False,True,False,False,False
2,2,0,53.85,108.15,1,False,True,True,False,True,...,False,False,False,True,True,False,False,False,False,False
3,3,0,42.30,1840.75,0,False,True,True,False,True,...,True,False,False,False,False,False,False,True,False,False
4,4,0,70.70,151.65,1,True,False,True,False,True,...,False,False,True,False,True,False,False,False,False,False

pd.read_csv('tel_churn_cleaned.csv')

This line uses pandas to read a CSV file (which is like an Excel spreadsheet saved in text form).

The file name is 'tel_churn_cleaned.csv'. It probably contains customer data about telecom churn (whether customers stay or leave).

The result is stored in a variable called df (short for dataframe), which is basically a table in Python.

df.head()

This shows the first 5 rows of the table.

It’s like peeking at the top of your spreadsheet to make sure the data looks correct.

In [49]:
df = df.drop('Unnamed: 0', axis = 1)

In [51]:
x = df.drop('Churn', axis = 1)
x

,SeniorCitizen,MonthlyCharges,TotalCharges,gender_Female,gender_Male,Partner_No,Partner_Yes,Dependents_No,Dependents_Yes,PhoneService_No,...,PaymentMethod_Bank transfer (automatic),PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check,tenure_group_1 - 12,tenure_group_13 - 24,tenure_group_25 - 36,tenure_group_37 - 48,tenure_group_49 - 60,tenure_group_61 - 72
0,0,29.85,29.85,True,False,False,True,True,False,True,...,False,False,True,False,True,False,False,False,False,False
1,0,56.95,1889.50,False,True,True,False,True,False,False,...,False,False,False,True,False,False,True,False,False,False
2,0,53.85,108.15,False,True,True,False,True,False,False,...,False,False,False,True,True,False,False,False,False,False
3,0,42.30,1840.75,False,True,True,False,True,False,True,...,True,False,False,False,False,False,False,True,False,False
4,0,70.70,151.65,True,False,True,False,True,False,False,...,False,False,True,False,True,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7027,0,84.80,1990.50,False,True,False,True,False,True,False,...,False,False,False,True,False,True,False,False,False,False
7028,0,103.20,7362.90,True,False,False,True,False,True,False,...,False,True,False,False,False,False,False,False,False,True
7029,0,29.60,346.45,True,False,False,True,False,True,True,...,False,False,True,False,True,False,False,False,False,False
7030,1,74.40,306.60,False,True,False,True,True,False,False,...,False,False,False,True,True,False,False,False,False,False
7031,0,105.65,6844.50,False,True,True,False,True,False,False,...,True,False,False,False,False,False,False,False,False,True

In [52]:
y = df['Churn']
y

0       0
1       0
2       1
3       0
4       1
       ..
7027    0
7028    0
7029    0
7030    1
7031    0
Name: Churn, Length: 7032, dtype: int64

In [53]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2)

train_test_split(x, y, test_size = 0.2)

This function splits your dataset into two parts:

Training set → the data used to teach the machine learning model.

Testing set → the data used to check if the model learned correctly.

x = the features (inputs, like customer age, monthly charges, contract type).

y = the target (output, like whether the customer churned or not).

test_size = 0.2 means 20% of the data will be used for testing, and 80% for training.

x_train, x_test, y_train, y_test

These are the four pieces created after splitting:

x_train → features for training.

x_test → features for testing.

y_train → labels (answers) for training.

y_test → labels for testing

**Decision Tree Classifier**

In [54]:
model_dt = DecisionTreeClassifier(criterion = 'gini', random_state = 100, max_depth = 6, min_samples_leaf = 8)

This line is creating a decision tree model with specific settings:

DecisionTreeClassifier(...)

This is the machine learning model you’re choosing: a decision tree.

A decision tree works like a flowchart of yes/no questions to classify data (e.g., “Is the customer on a monthly contract? Yes → High chance of churn”).

Parameters (the rules you set for the tree):

criterion = 'gini' → This tells the tree how to measure “purity” when splitting data.

Gini is a math formula that helps decide the best question to ask at each step.

random_state = 100 → Ensures the results are reproducible.

Think of it as fixing the “seed” so the tree grows the same way every time you run it.

max_depth = 6 → Limits the tree to 6 levels of questions.

Prevents the tree from becoming too complicated and memorizing the data (overfitting).

min_samples_leaf = 8 → Each final branch (leaf) must have at least 8 samples.

This avoids tiny branches that might be unreliable.

In [55]:
model_dt.fit(x_train, y_train)

DecisionTreeClassifier(max_depth=6, min_samples_leaf=8, random_state=100)

model_dt.fit(...)

This is the step where you train your decision tree model.

You’re feeding the model the training data (x_train → features, y_train → labels).

The model looks at the patterns in the features (like contract type, monthly charges, tenure) and learns how they connect to the target (whether the customer churned or not).

Result

After this line runs, your model is no longer “empty.”

It now has learned rules from the training data and is ready to make predictions.

In [56]:
y_pred = model_dt.predict(x_train)

model_dt.predict(...)

This tells your trained decision tree model to make predictions.

You’re asking it: “Based on what you’ve learned, what do you think the answers are for this data?”

x_train

Here, you’re giving the model the same training features it already studied (like customer age, contract type, monthly charges).

Normally, you’d use x_test (the unseen test data) to check performance.

Using x_train here is more like checking if the model memorized the training set correctly.

y_pred

This stores the model’s predictions (its guesses).

Each prediction corresponds to whether the model thinks a customer churned or not.

In [57]:
y_pred

array([0, 0, 1, ..., 0, 0, 0], shape=(5625,))

In [58]:
model_dt.score(x_test, y_test)

0.7761194029850746

**model_dt.score(...)**

This calculates how well your trained decision tree model performs.

It compares the model’s predictions on the test data (x_test) with the actual answers (y_test).

Since the outcome is **0.78**, that means the model is 78% accurate on the test data.

In [59]:
y_pred = model_dt.predict(x_test)
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.84      0.85      0.85      1031
           1       0.58      0.56      0.57       376

    accuracy                           0.78      1407
   macro avg       0.71      0.71      0.71      1407
weighted avg       0.77      0.78      0.77      1407

**classification_report** is a function from scikit-learn that generates a detailed performance report for your model.
**Classification_report(y_test, y_pred)** calls the function the your true labels (y_test) and your predicted labels (y_pred)

**The classification report gives you:**

Precision → Of all customers the model predicted as “churn,” how many were correct?

Recall → Of all customers who actually churned, how many did the model catch?

F1-score → A balance between precision and recall.

Support → How many samples were in each category.

This is much more detailed than just accuracy, and it’s especially important in churn prediction because catching churners (recall) can be more valuable than just overall accuracy.

In [79]:
from imblearn.combine import SMOTEENN

sm = SMOTEENN(random_state = 100)
x_resampled, y_resampled = sm.fit_resample(x, y)

In churn prediction, usually fewer customers churn compared to those who stay.

Without balancing, the model might ignore churners.

- SMOTEENN helps the model pay equal attention to both churners and non-churners, improving recall (catching actual churners).

* SMOTE (Synthetic Minority Oversampling Technique) → creates “new bananas” by slightly modifying existing ones (like making copies with small changes).

* ENN (Edited Nearest Neighbors) → cleans out noisy or confusing apples that don’t fit well.

**sm = SMOTEENN():** You are setting up a "Data Fixer" to handle the fact that you have way more "Stay" customers than "Churn" customers.

**sm.fit_resample(x, y):**

The "SMOTE" part: It looks at the customers who left and creates "synthetic" (fake but realistic) profiles of more customers who left. This gives the model more examples of "leaving behavior" to study.

The "ENN" part: It deletes the "noisy" data points—like a customer who looks exactly like someone who would stay, but left anyway for a random reason. This makes the patterns of "churning" much clearer for the computer.

The Result: x_resampled and y_resampled now contain a balanced mix of "Stayers" and "Leavers," so your model can't just take the easy way out by guessing "Stay" every time.

In [61]:
xr_train, xr_test, yr_train,yr_test = train_test_split(x_resampled, y_resampled, test_size = 0.2)


This code is doing exactly what was done earlier with train_test_split, but now it's applied to the balanced dataset after SMOTEENN resampling.

train_test_split(...)

Splits your resampled dataset into training and testing sets.

x_resampled = the balanced features (inputs like contract type, charges, tenure).

y_resampled = the balanced labels (outputs like churn = yes/no).

Resulting pieces:

xr_train → training features (80% of balanced data).

xr_test → testing features (20% of balanced data).

yr_train → training labels.

yr_test → testing labels.

test_size = 0.2

Means 20% of the balanced dataset is set aside for testing, while 80% is used for training.

In [62]:
model_dt_smote = DecisionTreeClassifier(criterion = 'gini', random_state = 100, max_depth = 6, min_samples_leaf = 8)

**DecisionTreeClassifier(...)** → same model type as before (a decision tree).

**criterion** = 'gini' → uses the Gini index to decide splits.

**random_state** = 100 → ensures reproducibility.

**max_depth** = 6 → limits the tree to 6 levels.

**min_samples_leaf** = 8 → requires at least 8 samples per leaf.

This is identical to your earlier tree, but now you’ll train it on the resampled data (xr_train, yr_train).

In [63]:
model_dt_smote.fit(xr_train, yr_train)
yr_predict = model_dt_smote.predict(xr_test)
model_score_r = model_dt_smote.score(xr_test, yr_test)
print(model_score_r)
print(metrics.classification_report(yr_test, yr_predict))

0.9222222222222223
              precision    recall  f1-score   support

           0       0.91      0.92      0.92       554
           1       0.93      0.92      0.93       616

    accuracy                           0.92      1170
   macro avg       0.92      0.92      0.92      1170
weighted avg       0.92      0.92      0.92      1170

* **model-dt_smote(..)**- Trains the decision tree (model_dt_smote) using the balanced training data.
  
* **yr_predict** - Makes predictions on the balanced test set.
  
* **model_score_r** - Calculates and prints the accuracy of the model on the balanced test set.

* **print(metrics.classification_report(...))** - prints a detailed performance report (precision, recall, F!-score, support) for each class.
  
Before balancing, your model probably had high accuracy but poor recall for churners (because churners were rare).

After SMOTEENN balancing, the model should:

Catch more churners (higher recall).

Be fairer across both classes.

Possibly trade a little accuracy for better balance — which is often more valuable in churn prediction.

In short: You’ve successfully retrained your decision tree on balanced data, and now you’re evaluating it with accuracy and a classification report to see how much better it performs at identifying churners.

In [64]:
print(metrics.confusion_matrix(yr_test, yr_predict))

[[512  42]
 [ 49 567]]

metrics.confusion_matrix(...) → Creates a table that compares the true labels (yr_test) with the predicted labels (yr_predict).

The output is a 2×2 matrix (for binary classification like churn vs. non-churn):

[[TN, FP]

[FN, TP]]

Where:

TN (True Negative) → Correctly predicted “no churn.”

FP (False Positive) → Predicted “churn” when it was actually “no churn.”

FN (False Negative) → Predicted “no churn” when it was actually “churn.”

TP (True Positive) → Correctly predicted “churn.”

* The confusion matrix is basically the scorecard showing where the child got it right and where they got confused.

Accuracy alone doesn’t tell the whole story.

The confusion matrix shows exactly where the model struggles:

If FN is high → the model is missing churners (bad for business).

If FP is high → the model is falsely flagging loyal customers as churners.

With SMOTEENN balancing, you should see better recall (fewer missed churners).

**Random Forest Classifier**

In [65]:
from sklearn.ensemble import RandomForestClassifier
model_rf = RandomForestClassifier(n_estimators = 100, criterion = 'gini', random_state = 100, max_depth = 6, min_samples_leaf = 8)

RandomForestClassifier(...) → Creates a Random Forest model, which is an ensemble of many decision trees.

n_estimators = 100 → Builds 100 decision trees and combines their results.

criterion = 'gini' → Each tree uses the Gini index to decide splits.

random_state = 100 → Ensures reproducibility.

max_depth = 6 → Limits each tree to 6 levels.

min_samples_leaf = 8 → Each leaf must have at least 8 samples.

In short: You’ve defined a Random Forest model with 100 trees, ready to be trained on your balanced dataset. This should give you stronger, more stable predictions compared to a single decision tree.

In [66]:
model_rf.fit(x_train, y_train)

RandomForestClassifier(max_depth=6, min_samples_leaf=8, random_state=100)

This line is trying to train your Random Forest model using x_train and y_train.

In [67]:
y_pred = model_rf.predict(x_test)
model_rf.score(x_test, y_test)

0.7853589196872779

model_rf.predict(x_test) → Uses your trained Random Forest model to make predictions on the test features (x_test).

model_rf.score(x_test, y_test) → Evaluates the model’s accuracy by comparing predictions against the true labels (y_test).

In [68]:
print(metrics.classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.82      0.90      0.86      1031
           1       0.63      0.48      0.54       376

    accuracy                           0.79      1407
   macro avg       0.73      0.69      0.70      1407
weighted avg       0.77      0.79      0.77      1407

metrics.classification_report(...) → Generates a detailed performance report for your model’s predictions.

It compares the true labels (y_test) with the predicted labels (y_pred).

The output includes:

Precision → Of all customers predicted as churners, how many were truly churners.

Recall → Of all actual churners, how many the model correctly identified.

F1-score → The balance between precision and recall.

Support → The number of samples for each class.

In [69]:
sm = SMOTEENN()
x_resampled1, y_resampled1 = sm.fit_resample(x, y)
xr_train1, xr_test1, yr_train1, yr_test1 = train_test_split(x_resampled1, y_resampled1, test_size = 0.2)
model_rf_smote = RandomForestClassifier(n_estimators = 100, criterion = 'gini', random_state = 100, max_depth = 6, min_samples_leaf = 8)

**Why this matters**

Using xr_train1, yr_train1 ensures you’re training on the balanced dataset.

Testing on xr_test1, yr_test1 shows how well the model generalizes after balancing.

The classification report and confusion matrix will reveal whether recall for churners has improved compared to the original imbalanced dataset.

In [70]:
model_rf_smote.fit(xr_train1, yr_train1)

RandomForestClassifier(max_depth=6, min_samples_leaf=8, random_state=100)

In [89]:
import joblib
joblib.dump(model_rf_smote, "model_rf_smote.pkl")

['model_rf_smote.pkl']

model_rf_smote → Your Random Forest model (100 trees, Gini criterion, depth 6, min leaf 8).

.fit(xr_train1, yr_train1) → Trains the model using the balanced training set created by SMOTEENN (xr_train1, yr_train1).

In [71]:
yr_predict1 = model_rf_smote.predict(xr_test1)
model_score_r1 = model_rf_smote.score(xr_test1, yr_test1)
print(model_score_r1)
print(metrics.classification_report(yr_test1, yr_predict1))

0.922165820642978
              precision    recall  f1-score   support

           0       0.96      0.87      0.91       546
           1       0.90      0.97      0.93       636

    accuracy                           0.92      1182
   macro avg       0.93      0.92      0.92      1182
weighted avg       0.92      0.92      0.92      1182

**model_rf_smote.predict(...):** Makes predictions on the balanced test set (xr_test1).

**model_score_r1 = model_rf_smote.score(...)**

**print(model_score_r1):** Calculates and prints the accuracy of the model on the balanced test set.

**print(metrics.classification_report(...)):** Prints a detailed performance report (precision, recall, F1-score, support) for each class.

In [72]:
print(metrics.confusion_matrix(yr_test1, yr_predict1 ))

[[475  71]
 [ 21 615]]

**Performing PCA** (Principal Component Analysis)

In [73]:
# Applying PCA
from sklearn.decomposition import PCA
pca = PCA(0.9)
xr_train_pca = pca.fit_transform(xr_train1)
xr_test_pca = pca.transform(xr_test1)
explained_variance = pca.explained_variance_ratio_

Building on our "Super Column" analogy, this code is telling the computer: "Shrink my data, but don't lose the important stuff."

Here is the breakdown of what each line is doing to your churn data:

from sklearn.decomposition import PCA: You are reaching into the Scikit-Learn toolkit and grabbing the PCA "Compressor" tool.
pca = PCA(0.9): This is the most important part. By putting 0.9 inside the brackets, you are giving a specific instruction: "Create enough 'Super Columns' to keep 90% of the original information (variance), and throw away the 10% that is just noisy junk."

xr_train_pca = pca.fit_transform(xr_train1):
**Fit:** The computer studies your training data to find the best way to combine your 50+ columns into "Super Columns."
Transform: It then actually "squashes" the data down into those new columns.

xr_test_pca = pca.transform(xr_test1): You apply the exact same squash to your test data. Notice there is no "fit" here—you want to treat the test data exactly how you treated the training data so the "exam" is fair.

explained_variance = pca.explained_variance_ratio_: This creates a list showing how much "power" each new Super Column has. For example, if the first number is 0.70, it means Super Column 1 alone holds 70% of all the information about why customers stay or leave.

The Essence for your Churn Model:
Before this code, your xr_train1 might have had 50 columns. After this code, xr_train_pca might only have 10 or 15 columns, but those columns are so "dense" with information that your model will run faster and be less likely to get "distracted" by minor, irrelevant details.

In [74]:
model = RandomForestClassifier(n_estimators = 100, criterion = 'gini', random_state = 100, max_depth = 6, min_samples_leaf = 8)
model.fit(xr_train_pca, yr_train1)

RandomForestClassifier(max_depth=6, min_samples_leaf=8, random_state=100)

This code is like hiring a "Committee of 100 Experts" (Random Forest) and giving them very specific rules on how to judge whether a customer will churn.
Since you are using xr_train_pca, you are giving these experts the "Super Columns" we talked about earlier instead of the raw, messy data.

Line-by-Line Breakdown:
n_estimators = 100: This tells the computer to build 100 Decision Trees. Each tree will look at the data slightly differently, and they will vote at the end to give you a final answer.

criterion = 'gini': This is the "Math Rule" the trees use to decide how to split the data. Think of it as a "Purity Test." The tree asks questions that try to separate "Churners" from "Stayers" as cleanly as possible.

random_state = 100: This is your "Save Slot." It ensures that if you run this code again, the 100 trees are built in the exact same way so your results don't change.

max_depth = 6: This is a "Safety Limit." It tells each tree, "You can only ask 6 questions before you have to make a decision." This stops the trees from becoming too complex and "over-memorizing" the data.

min_samples_leaf = 8: This means a "branch" on the tree must represent at least 8 customers to be valid. If a pattern only applies to 1 or 2 weird customers, the tree is told to ignore it. This keeps the model focused on general trends rather than individual outliers.

model.fit(xr_train_pca, yr_train1): This is the "Study Session." The 100 trees look at the "Super Columns" (xr_train_pca) and the correct answers (yr_train1) to learn the patterns of churn.

Why these specific settings?

By setting max_depth and min_samples_leaf, you are intentionally making the trees "simpler." This is a smart move in Churn Prediction because it helps the model work well on new, future customers rather than just being perfect on the old data you already have.

In [75]:
yr_predict_pca = model.predict(xr_test_pca)
model_score_r_pca = model.score(xr_test_pca, yr_test1)

Building on our previous analogies, this code is the "Final Exam" for your committee of 100 experts.

Since you trained them using the "Super Columns" (PCA), you are now testing them to see if they can accurately predict churn on data they have never seen before.

**Line-by-Line Breakdown:**

yr_predict_pca = model.predict(xr_test_pca):

The Action: You are handing the "Super Columns" of your test group (xr_test_pca) to your Random Forest.

Layman's terms: This is the model actually taking the test. It looks at the simplified patterns it learned and writes down its "Guess" (Churn or Stay) for every single customer in that list.

The Result: All those guesses are saved in a new list called yr_predict_pca.

model_score_r_pca = model.score(xr_test_pca, yr_test1):
The Action: This is a quick way to get the Accuracy Percentage.

Layman's terms: The computer looks at the model's guesses, compares them to the "Answer Key" (yr_test1), and gives you a single number (like 0.78).

The Result: If it shows 0.78, it means your model got 78% of the questions right.

Why is there a "_pca" at the end of the names?

In coding, this is a best practice. By adding _pca to your variables, you are keeping this model's results separate from your previous model (the one that used all the messy, original columns). This allows you to compare them side-by-side.

The Moment of Truth:

If your model_score_r_pca is higher than your original score, it means the PCA "Super Columns" successfully cleared away the noise and helped the model see the truth more clearly.

In [76]:
print(model_score_r_pca)
print(metrics.classification_report(yr_test1, yr_predict_pca))

0.7428087986463621
              precision    recall  f1-score   support

           0       0.77      0.63      0.69       546
           1       0.72      0.84      0.78       636

    accuracy                           0.74      1182
   macro avg       0.75      0.73      0.74      1182
weighted avg       0.75      0.74      0.74      1182

**Pickling the model**

In [77]:
import pickle
import joblib

filename = 'model.sav'

pickle.dump(model_rf_smote, open(filename, 'wb'))

load_model = pickle.load(open(filename, 'rb'))

**import pickle / import joblib**

These are Python tools for saving and loading models. Think of them as the “Save” and “Open” buttons for your trained machine learning model.

**filename = 'model.sav'**

You’re giving your model a name (model.sav) so it can be stored as a file on your computer. Like saving a Word document as report.docx.

**pickle.dump(model_rf_smote, open(filename, 'wb'))**

This line saves your trained Random Forest model (model_rf_smote) into the file model.sav. 'wb' means “write in binary mode” — the computer stores it in a format it can read back later.

**load_model = pickle.load(open(filename, 'rb'))**

This line loads the saved model back into memory. 'rb' means “read in binary mode.” It’s like reopening your saved Word document to continue working.

In [78]:
model_score_r1 = load_model.score(xr_test1, yr_test1)
model_score_r1

0.922165820642978

**model_score_r1 = load_model.score(xr_test1, yr_test1)**

Now you test the loaded model on your test data (xr_test1, yr_test1).

.score() gives you the accuracy — how well the model predicts correctly.

**model_score_r1**

Finally, you print the accuracy score. This confirms that the saved and reloaded model works exactly the same as before.

**👉 In short:** This code is like saving your trained model to a file and reopening it later to check that it still works. It’s the bridge between your Jupyter notebook experiments and a real churn prediction app you can deploy.

**Difference between Decision Tree & Random Forest**

Think of these two models as a Manager versus a Committee.

1. **Decision Tree (The Single Manager):**
Imagine you have one manager deciding if a customer will churn (leave). They use a flow chart of "Yes/No" questions:

"Has the customer been with us for less than 6 months?" → Yes

"Do they have a high monthly bill?" → Yes

"Have they called support 3 times this month?" → Yes

Result: Prediction = Churn.

**The Downside:** A single manager might be biased or "overthink" a specific customer's weird habits (this is called Overfitting). If that one manager is wrong, the whole prediction is wrong.

2. **Random Forest (The Committee):** A Random Forest is just a large group (a "forest") of many Decision Trees working together.

**How it works:**
The Crowd: Instead of one manager, you hire 100 managers.

Different Perspectives: You don't give every manager the same data. You give each one a slightly different "shuffled" version of the customer list and only show them a few specific details (like only their "Contract Type" or only their "Internet Speed").

The Vote: Each tree makes its own independent "Yes/No" prediction.

The Final Answer: You take a vote. If 80 trees say "Churn" and 20 say "Stay," the Random Forest predicts Churn.

**Why is the Forest better?**

"The Wisdom of the Crowd."

Even if a few trees get confused by a weird data point, the majority of the trees will usually pull the answer back to the truth. This makes the Random Forest much more stable and accurate than a single Decision Tree.

In the project:
Decision Tree: Might focus too hard on one specific rule.
Random Forest: Will look at the "big picture" of your customer data

**Confusion Matrix**

Think of a Confusion Matrix as a "Truth Table" or a Report Card that shows exactly where your model is getting its "answers" right and where it is getting confused. 

* Why is it called "Confusion"?

The name comes from the fact that the table literally shows you which categories your model is confusing with others. For example, in your churn project, it will show you how many people the model "confused" for stayers when they were actually about to leave

**Principal Component Analysis**

PCA stands for Principal Component Analysis — it’s a technique in machine learning and statistics used for dimensionality reduction.

In short: PCA is a way to compress your dataset into fewer dimensions while keeping most of the important information. It’s especially useful when you have many features, like in your churn prediction project.

**What PCA does, it:**

Takes a dataset with many features (columns).

Finds new “directions” (called principal components) that capture the most variance (information) in the data.

Projects the data onto these components, reducing the number of dimensions while keeping most of the important information.

**Interpretation of each Model_Score**

This is the most important "Aha!" moment in your learning so far. At first glance, it looks like the Decision Tree (92%) is the winner, but in the world of Churn Prediction, it is likely the biggest liar.

Here is how to interpret these results in layman's terms:

1. The Decision Tree (92%) – "The Student who Memorized the Practice Test"
In machine learning, we call this Overfitting.

What happened: A single Decision Tree is very "bossy." Because you didn't give it strict rules (like max_depth), it likely memorized every single specific detail of your training data—even the random coincidences.

The Churn Effect: If a customer named "John" left and he happened to wear a "Red Shirt," the tree might make a rule: "Everyone in a Red Shirt will leave." This works perfectly on your current data, but it will fail miserably on new, real-world customers who don't fit that exact pattern.

2. The Random Forest (78%) – "The Wise Committee".
This is likely your most reliable model.

What happened: By using 100 trees and setting rules like max_depth=6, you forced the model to look at general trends instead of memorizing individuals. It dropped from 92% to 78% because it stopped "cheating" by memorizing and started actually "learning."

The Churn Effect: This model is more "robust." It will probably perform much better on next month's customer data than the Decision Tree will.

1. The PCA Model (70%) – "The Simplified View"
What happened: By using PCA, you threw away 10% of your data's information to make it simpler. In this case, you might have thrown away a few details that were actually important for predicting churn.

The Churn Effect: While 70% is lower, it tells us that even with a "blurry" version of the data, the model can still get 7 out of 10 customers right.

**The Verdict for your Project:**

In a Churn Project, High Accuracy is often a Trap.
If 90% of your customers stay, a "dumb" model can get 90% accuracy just by guessing "Stay" every time—but it will miss 100% of the people who actually leave.

To find the real winner, you must look at the "Recall" for the "Churn" class:
Check your classification_report for each model.

Look for the Recall score for Class 1 (the Churners).
The model with the highest Recall for Churn is your true winner, because that’s the one that actually "caught" the most people before they left.

**FOR MY PRESENTATION PURPOSE**

**Customer churn prediction overview**

Customer churn prediction predicts the likelihood of customers canceling a company’s products or services. In most cases, businesses with repeat clients or clients under subscriptions strive to maintain the customer base. Therefore, it is important to keep track of the customers who cancel their subscription plan and those who continue with the service. This approach requires the organization to know and understand their client’s behavior and the attributes that lead to the risk of the client leaving. I will explain the steps necessary in creating and deploying a churn prediction machine-learning model.

Why Predict Customer Churn?

It is important for any organization dealing with repeat clients to find ways to retain existing ones. The approach is crucial since customer churn is expensive, and acquiring new clients is more expensive than retaining existing ones. Consider an internet service (ISP) provider who has acquired a new user. They will need technicians and hardware to connect the latest client to their service. The client will only be required to pay the subscription fee to continue using their plan. If the user fails to renew their service, the company will most likely be at a loss, especially if the trend continues for several customers. The monthly recurring revenue (MRR) for such an institution will likely be low; hence, it will be unable to sustain the business. Thus, a reliable churn prediction model should help companies stay afloat as they scale up and attract more customers.

Case Study of Customer Churn Prediction Model

Creating churn prediction models involves using historical customer data to predict the likelihood of the current customer leaving or continuing with a particular service/product. The data used for the predictive models include product usage data and direct customer feedback. Besides, the predictive models identify the different trends and patterns in the data to forecast customer churn.

Scenario

Consider an e-commerce company with historical data on how its clients have interacted with its services. The company wants to know the likelihood of customers churning so it can launch targeted marketing campaigns.